# Generated by Django 2.2.7 on 2019-11-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20191022_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.CharField(blank=True, default='contacts', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True, default='experience', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='link',
            field=models.URLField(blank=True, default='link', null=True),
        ),
    ]
