# Generated by Django 2.2.7 on 2019-11-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20191106_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='link',
            new_name='github',
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
