# Generated by Django 2.2.6 on 2019-11-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20191106_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
