# Generated by Django 2.2.6 on 2019-11-06 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0013_auto_20191106_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insta.Profile'),
        ),
    ]
