# Generated by Django 2.2.6 on 2019-11-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0014_level_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
