# Generated by Django 2.2.6 on 2019-11-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0017_auto_20191106_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insta.Levels'),
        ),
    ]
