# Generated by Django 2.2.6 on 2019-11-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0020_auto_20191107_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Junior', 'Junior'), ('Intermediate', 'Intermediate'), ('Senior', 'Senior')], default='Junior', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
