# Generated by Django 2.2.6 on 2019-11-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0022_auto_20191107_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Senior', 'Senior')], default='Junior', max_length=20),
        ),
    ]
